-- MySQL Script generated by MySQL Workbench
-- Wed Mar 10 23:24:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_store` DEFAULT CHARACTER SET utf8 ;
USE `db_store` ;

-- -----------------------------------------------------
-- Table `db_store`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_store`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `type` INT NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `adress` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `db_store`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_store`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `category_description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `db_store`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_store`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(100) NOT NULL,
  `product_description` TEXT NULL DEFAULT NULL,
  `img_path` VARCHAR(100) NULL DEFAULT NULL,
  `price` FLOAT NOT NULL,
  `product_quantity` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_store`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_store`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `amount` FLOAT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_store`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_store`.`order_detail` (
  `order_detail_id` INT NOT NULL AUTO_INCREMENT,
  `order_detail_quantity` INT NOT NULL,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`order_detail_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
